#spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3306/mydb
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: myuser
#    password: mypass
#  jpa:
#    hibernate:
#      ddl-auto: none     # 운영에서는 자동 생성 금지
#    show-sql: false